version: '3.8'

services:
  web:
    build: .
    container_name: php_web
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=help_with_homework

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: help_with_homework
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/install.sql:/docker-entrypoint-initdb.d/1.sql
      - ./sql/example.sql:/docker-entrypoint-initdb.d/2.sql

volumes:
  db_data:
